### ISSUE TITLE
PyCharm: Environment variable $TERM_PROGRAM is unset.

### ISSUE THREAD

**Issue by anki-code** [jnoortheen/xontrib-cmd-durations#13]
Hi! Thank you for the awesome xontrib!

I've faced with this in [PyCharm Community Edition](https://www.jetbrains.com/pycharm/download/#section=mac) [terminal](https://www.jetbrains.com/help/pycharm/terminal-emulator.html):
```xsh
xontrib load cmd_done
sleep 6
# WARNING:root:Environment variable $TERM_PROGRAM is unset. 
# It should be set by the terminal application on shell startup. Not able to find active window.
```
Because:
```xsh
env | grep TERM
#TERM=xterm-256color
#TERMINAL_EMULATOR=JetBrains-JediTerm
#TERM_SESSION_ID=77455237-439e-4631-87d5-0c33757ebcdf
```

And the notification will be appear no matter for the terminal is focused or not.

What is the right way to solve this?

Thanks!

## For community

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
Could you post the OS and what shell backend is used by the pycharm terminal? I think one solution would be to set `$TERM_PROGRAM` manually.

**Comment by jnoortheen** [comment]
Yes the feature doesn't work on Windows as noted. I don't use Windows but happy to accept any fixes.

**Comment by jnoortheen** [comment]
Yes I understand, in that case I suggested setting the environment variable. You haven't answered the shell it is using, I guess it to be zsh (the default on MacOS). Please check why it is not setting the terminal program variable.
