### ISSUE TITLE
Fix repo About

### ISSUE THREAD

**Issue by anki-code** [jnoortheen/xontrib-cmd-durations#5]
Current description: "xontrib to send notification once long running command is finished. Adds durations PROMPT_FIELDS "

Should be like this: "Send notification once long running command is finished in the xonsh shell."

Thanks!

**Comment by jnoortheen** [comment]
Hey @anki-code , I think this is more descriptive (though verbose), `Show long running commands durations in prompt with option to send notification when terminal is not focused.` what do you think?

**Comment by anki-code** [comment]
Yeah!
