### ISSUE TITLE
Crop the notification image and add the long version to preview

### ISSUE THREAD

**Issue by anki-code** [jnoortheen/xontrib-cmd-durations#6]
I think it should looks like:

![image](https://user-images.githubusercontent.com/1708680/144043617-3c09ef32-a208-4065-a305-ece17013e9d1.png)

And also it will be great to add the 640x320 image to the repo settings for preview:

![image](https://user-images.githubusercontent.com/1708680/144043888-e5540cf0-aad2-48d9-a92e-bcf459f87ed0.png)

**Comment by jnoortheen** [comment]
@anki-code do you mean the image in readme page?

**Comment by anki-code** [comment]
yep
